services:

  chatbot:
    build:
      context: chatbot
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./chatbot:/code
    command: sh -c "uvicorn chatbot.web.application:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - weaviate


  weaviate:
    image: semitechnologies/weaviate:1.25.11
#    ports:
#      - '8080:8080'
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'
      ENABLE_MODULES: 'backup-filesystem'
      BACKUP_FILESYSTEM_PATH: '/tmp/backups'
      AUTOSCHEMA_ENABLED: 'false'
    volumes:
      - weaviate_data:/var/lib/weaviate
      - ./weaviate/backups:/tmp/backups

volumes:
  weaviate_data:
