#
# This is an example configuration file for the chatbot.
# To use it, copy it to `config.yml` and replace the placeholders with your own values.
#

openai:
  api_key: 'replace-with-openai-api-key'

google:
  api_key: 'replace-with-google-api-key'

langsmith:
  api_key: 'replace-with-langsmith-api-key'
  tracing: true
  endpoint: 'https://api.smith.langchain.com'
  project: 'default'

huggingface:
  embedding_model_name: 'sentence-transformers/all-mpnet-base-v2'

weaviate:
  http_host: 'weaviate'
  http_port: 8080
  http_secure: false
  grpc_host: "weaviate"
  grpc_port: 50051
  grpc_secure: false

data_sources:
  course_csv_file: 'data/courses.csv'
