#
# This is an example configuration file for the chatbot.
# To use it, copy it to `config.yml` and replace the placeholders with your own values.
#

openai:
  api_key: 'override-with-openai-api-key'
  model: 'gpt-3.5-turbo'

google:
  api_key: 'override-with-google-api-key'

langsmith:
  api_key: 'override-with-langsmith-api-key'
  tracing: true
  endpoint: 'https://api.smith.langchain.com'
  project: 'default'

huggingface:
  embedding_model_name: 'WhereIsAI/UAE-Large-V1'

weaviate:
  http_host: 'weaviate'
  http_port: 8080
  http_secure: false
  grpc_host: "weaviate"
  grpc_port: 50051
  grpc_secure: false

data_sources:
  courses_csv_file: 'data/courses.csv'
  programs_csv_file: 'data/programs.csv'

text_splitter:
  chunk_size: 12000
  chunk_overlap: 1500
  add_start_index: true